//! Embeds the vendored Svelte runtime (`runtime/dist`) into the crate and
//! computes a content hash of it.
//!
//! The vendored files are produced by the maintainer-only `runtime/build.mjs`
//! and committed. This script generates a table of `(served path, contents)`
//! pairs plus `RUNTIME_HASH`, so the crate serves the runtime from memory with
//! no filesystem access at run time. Application builds never run Node.

use std::{fs, path::Path};

use sha2::{Digest, Sha256};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dist_dir = Path::new(&manifest_dir).join("runtime").join("dist");

    println!("cargo:rerun-if-changed={}", dist_dir.display());

    let mut files = Vec::new();
    collect_files(&dist_dir, &dist_dir, &mut files);
    // Sort for a stable hash and deterministic generated output.
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let mut hasher = Sha256::new();
    let mut entries = String::new();
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={abs}");
        let bytes = fs::read(abs).unwrap();
        hasher.update(rel.as_bytes());
        hasher.update([0u8]);
        hasher.update(&bytes);
        hasher.update([0u8]);
        entries.push_str(&format!("    ({rel:?}, include_str!({abs:?})),\n"));
    }

    let hash = hasher.finalize();
    let hash_hex: String = hash.iter().take(8).map(|b| format!("{b:02x}")).collect();

    let generated = format!(
        "// @generated by build.rs from runtime/dist -- do not edit.\n\
         pub(crate) static RUNTIME_FILES: &[(&str, &str)] = &[\n{entries}];\n\
         pub(crate) const RUNTIME_HASH: &str = {hash_hex:?};\n"
    );

    let out_dir = std::env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("runtime_files.rs"), generated).unwrap();
}

/// Recursively collects `(served-path, absolute-path)` pairs under `dir`, where
/// the served path is relative to `root` and uses `/` separators.
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let mut children: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .map(|e| e.unwrap().path())
        .collect();
    children.sort();
    for path in children {
        if path.is_dir() {
            collect_files(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path.to_string_lossy().into_owned()));
        }
    }
}
